Bugfix pwm
Infineon/micropython pull request #120
Opened 2024-02-12 12:49 UTC by NikhitaR-IFX

By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
- Fixed calculations in PWM duty_u16 --> get and set functions
- Set duty_ns using pwm_duty_set_ns()
- Implemented DUT tests for PWM
- Removed invert functionality as this is currently not working and enabling this requires more efforts which challenges the current implementation of the module.

Related Issue
[DESMAKERS-3621](https://jirard.intra.infineon.com/browse/DESMAKERS-3621)

2024-02-12 14:59 UTC, jaenrig-ifx requested changes
Nice 👍  Only missing thing is the docs, making a note that "invert" is not available. Also update any example using "invert".

2024-02-12 16:17 UTC, IFX-Anusha approved these changes

2024-02-13 05:54 UTC, NikhitaR-IFX commented
> Nice 👍 Only missing thing is the docs, making a note that "invert" is not available. Also update any example using "invert".

Thanks for noticing. Done now.

2024-02-13 08:00 UTC, jaenrig-ifx approved these changes

2024-02-13 08:28 UTC, merged