docs/psoc6: Fix Documentation.
Infineon/micropython pull request #160
Opened 2024-07-17 12:40 UTC by IFX-Anusha

Find the updated documentation here: 
https://ifx-micropython.readthedocs.io/en/document-review/psoc6/quickref.html

2024-07-17 13:57 UTC, jaenrig-ifx approved these changes
Nice!

2024-07-18 07:08 UTC, NikhitaR-IFX approved these changes
Looks good! 🚀

2024-07-18 12:46 UTC, ramya-subramanyam approved these changes
Looks good!

2024-07-19 06:32 UTC, ederjc requested changes
There are still typos, grammar problems and inconsistencies in the documentation. Please go through the whole document and correct these before I review the whole document.

To be more efficient in a first review iteration it can also be helpful to ask an AI to go through the document, e.g.
```
The following document is a RST file for a documentation on read the docs. Please review it for parsing errors, typos, grammar, language, consistency and so on. The output should be comments for a pull request in form of
<line number>: Comment/feedback/improvement suggestion
```

2024-07-19 06:32 UTC, ederjc commented on docs/psoc6/quickref.rst
### Comments from me until line 377 (I am running out of time for further review)

- 59: Add dot at end of sentence
- How do we decide if we use note or warning?
- 175: Pls use proper source code formatting in docs (e.g. Pin.OUT)
- 210: "board-specific", space after "capable pins.", "the frequency argument is optional"
- 228: Missing space
- 252: "parameters:"
- 257: "8-bit integer"
- 260: "it is set"
- How do we decide if we use code formatting in docs? I think there are some inconsistencies there
- 364, 365: sec/secs -> seconds
- 365: "Also," (https://english.stackexchange.com/a/339030)
- 377: "Feed the WDT. Do this periodically before the timeout."
- Under each module there is written "See <link>", shouldn't this end with a dot?
- Under some modules there is written "The `...` module", shouldn't this end with a dot?

### Comments from AI (some are wrong, some are helpful - handle with care)
Here are the comments, feedback, and improvement suggestions for the provided RST file:

---

**General Comments:**
1. Ensure all trademarks like "PSoC6™" are used consistently throughout the document.
2. "MicroPython REPL" and other terms specific to the platform should be capitalized consistently.
3. For consistency, units of measure should be followed immediately by the value (e.g., "1000 ns" instead of "1000ns").

---

**Specific Line-by-Line Comments:**

**Line 8:** 
- Comment: Add a period at the end of the sentence.
- Feedback: "The CY8CPROTO-062-4343W PSoC6™ Board."

**Line 12:** 
- Comment: The sentence can be clearer.
- Improvement: "If this is your first time working with this port, it may be useful to get an overview of the microcontroller."

**Line 20:** 
- Typo: "built-in" should be "built-in."
- Feedback: "The PSoC6™ port is now a mature port and is expected to support any MicroPython built-in library."

**Line 22:** 
- Grammar: "certainly" is redundant here.
- Improvement: "only the listed and documented modules in this quick reference are supported."

**Line 54:** 
- Typo: Adjust spacing and add a period.
- Feedback: "timing (high_time_0, low_time_0, high_time_1, low_time_1) in ns."
- Feedback: "bitstream buffer data with timing through pin P13_6."

**Line 60:** 
- Grammar: "works" should be "work."
- Feedback: "All timings greater than 1500 ns work, and the accuracy of the timing is +/- 400 ns."

**Line 73:** 
- Typo: "timing related" should be "timing-related."
- Feedback: "Use the :mod:`time <time>` module:"

**Line 108:** 
- Grammar: Consider rephrasing for clarity.
- Feedback: "Additionally, with any combination of parameters (except the Pin number or `id`, which must be passed), a :mod:`machine.Pin` object with various configurations can be instantiated."

**Line 133:** 
- Typo: "keywords" should be "keyword arguments."
- Feedback: "The parameters can be passed in any order if keyword arguments are used."

**Line 170:** 
- Typo: "PIN.IRQ_FALLING||PIN.IRQ_RISING" should be consistent in formatting.
- Feedback: "Trigger can be `Pin.IRQ_FALLING`, `Pin.IRQ_RISING`, or `Pin.IRQ_FALLING | Pin.IRQ_RISING`."

**Line 272:** 
- Typo: "datsheets" should be "datasheets."
- Feedback: "Refer to board-specific datasheets here for details regarding all the I2C-capable pins."

**Line 274:** 
- Grammar: "by default" should be "is set to 400 KHz by default."
- Feedback: "If the frequency is not specified, it defaults to 400 KHz."

**Line 333:** 
- Grammar: Adjust spacing and punctuation.
- Feedback: "Part of the functionality of the I2C slave is based on hardware interrupts and callbacks."

**Line 431:** 
- Typo: "manadatorily" should be "mandatory."
- Feedback: "All four arguments must be passed to create a PWM object. Only one of `duty_u16` or `duty_ns` should be specified."

**Line 551:** 
- Typo: "initialising" should be "initializing."
- Feedback: "The pins `sck`, `mosi`, and `miso` must be specified when initializing the SPI."

**Line 569:** 
- Typos: Multiple issues in this line.
- Feedback: "Construct and return a new SPI slave object using the following parameters."

**Line 618:** 
- Typo: "initialise" should be "initialize."
- Feedback: "Initialize the UART with the given parameters."

**Line 659:** 
- Grammar: Adjust phrasing for consistency.
- Feedback: "The handler will be called when the trigger condition is met."

**Line 702:** 
- Typo: "datsheets" should be "datasheets."
- Feedback: "Refer to board-specific datasheets here for details regarding the SPI-capable pins."

---

Consider revising the document according to these suggestions for a more polished and professional presentation.

2024-07-23 08:48 UTC, ederjc approved these changes

2024-07-24 05:06 UTC, merged