Fix machine obj instances
Infineon/micropython pull request #163
Opened 2024-07-22 11:31 UTC by IFX-Anusha

- Moved Machine object configs to board-specific files

- Limited the Max of machine objects for each machine class to the actual ones available in that board.

2024-07-22 12:38 UTC, jaenrig-ifx approved these changes
Perfect 🙌

2024-07-22 13:03 UTC, ramya-subramanyam requested changes
Looks good!

Just 1 question... Shouldn't NETWORK_WLAN_MAX_AP_STATIONS and MAX_WHD_INTERFACE defines also go into board config? I saw them network_ifx_wcm.c module. Although it is not machine module, it makes sense in board configs right?

2024-07-22 13:16 UTC, jaenrig-ifx commented
> Looks good!
> 
> Just 1 question... Shouldn't NETWORK_WLAN_MAX_AP_STATIONS and MAX_WHD_INTERFACE defines also go into board config? I saw them network_ifx_wcm.c module. Although it is not machine module, it makes sense in board configs right?

Not really... 

MAX_WHD_INTERFACE is redefined here, because that define is not present in the MPY built. But actually, this is set by the whd driver, not by our MPY layer..

NETWORK_WLAN_MAX_AP_STATIONS is the number of stations that will be listed when requesting an access point status (ap.status('stations')) to an access point. It is up to this class to define how many stations you want to list (given the limitations of the cy_wcm_get_associated_client_list(), which is technically 256).

2024-07-23 06:49 UTC, ramya-subramanyam approved these changes

2024-07-23 10:30 UTC, NikhitaR-IFX approved these changes

2024-07-24 06:33 UTC, merged